// projects
export const REQUEST_PROJECT = 'REQUEST_PROJECT';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';

// documents
export const REQUEST_PROJECT_DOCUMENTS = 'REQUEST_PROJECT_DOCUMENTS';
export const RECEIVE_PROJECT_DOCUMENTS = 'RECEIVE_PROJECT_DOCUMENTS';

// bids
export const CREATE_BIDS_FAILED    = 'CREATE_BIDS_FAILED';
export const CREATE_BIDS_SUCCEEDED = 'CREATE_BIDS_SUCCEEDED';
export const CREATE_BIDS_PENDING   = 'CREATE_BIDS_PENDING';

// questions
export const READ_QUESTIONS_PENDING   = 'READ_QUESTIONS_PENDING';
export const READ_QUESTIONS_FAILED    = 'READ_QUESTIONS_FAILED';
export const READ_QUESTIONS_SUCCEEDED = 'READ_QUESTIONS_SUCCEEDED';

// paints
export const RECEIVE_PAINT_PROJECT = 'RECEIVE_PAINT_PROJECT';

// electricals
export const RECEIVE_ELECTRICAL_PROJECT = 'RECEIVE_ELECTRICAL_PROJECT';

// countertops
export const RECEIVE_COUNTERTOP_PROJECT = 'RECEIVE_COUNTERTOP_PROJECT';
